FROM golang:alpine AS builder

# 为我们的镜像设置必要的环境变量
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# 移动到工作目录：/build
WORKDIR /build

# 将代码复制到容器中
COPY go.mod .
COPY go.sum .
# 下载依赖信息
RUN go mod download

#将代码复制到容器中
COPY . .



# 将我们的代码编译成二进制可执行文件
RUN go build -o {{ .Name }}_app .

###################
# 接下来创建一个小镜像
###################
FROM debian:bullseye-slim

# 从builder镜像中把静态文件拷贝到当前目录
COPY ./wait-for.sh /
#COPY ./templates /templates
#COPY ./static /static

# 从builder镜像中把配置文件拷贝到当前目录
COPY ./conf /conf

# 从builder镜像中把/dist/app 拷贝到当前目录
COPY --from=builder /build/{{ .Name }}_app /

RUN set -eux; \
	apt update; \
	apt install -y \
		--no-install-recommends \
		netcat; \
        chmod 755 wait-for.sh

#声明服务端口
EXPOSE 8888

# 需要运行的命令
ENTRYPOINT ["/{{ .Name }}_app"]
